name       : navi
version    : 2.14.0
release    : 5
source     :
    - https://github.com/denisidoro/navi/archive/v2.14.0.tar.gz : 544c01e9d10dfcdcdded7758411e90d69e9b4734dfda1c0908359a72ba7b2bee
license    : Apache-2.0
component  : system.utils
summary    : An interactive cheatsheet tool for the command-line and application launchers
description: |
    Navi allows you to browse through cheatsheets (that you may write yourself or download from maintainers) and execute commands
networking : yes
builddeps  :
    - cargo
rundeps    :
    - fzf
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/navi $installdir/usr/bin/navi
