name       : navi
version    : 2.7.0
release    : 2
source     :
    - https://github.com/denisidoro/navi/archive/v2.7.0.tar.gz : 47a6aa786702eb5387e9bc77790749d77240835293982cffc9ba3a329a359c13
license    : Apache-2.0
component  : system.utils
summary    : 
    An interactive cheatsheet tool for the command-line and application launchers
description: |
    Navi allows you to browse through cheatsheets (that you may write yourself or download from maintainers) and execute commands
networking : yes
builddeps  : 
    cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/navi $installdir/usr/bin/navi
