name       : navi
version    : 2.6.1
release    : 1
source     :
    - https://github.com/denisidoro/navi/archive/v2.6.1.tar.gz : 2d25a5bf62c65418861fc6857e60815d271fcf4f1b5a73170c8761a258c695cc 
license    : Apache-2.0
component  : system.utils
summary    : 
    An interactive cheatsheet tool for the command-line and application launchers
description: |
    Navi allows you to browse through cheatsheets (that you may write yourself or download from maintainers) and execute commands
networking : yes
builddeps  : 
    cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/navi $installdir/usr/bin/navi
